-- Mirrors the Flyway-managed production schema exactly: NOT NULL with a DEFAULT TRUE.
DROP TABLE IF EXISTS t_inherited_dynamic_insert;
CREATE TABLE t_inherited_dynamic_insert (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(255)     NULL,
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE
);

DROP TABLE IF EXISTS t_declared_dynamic_insert;
CREATE TABLE t_declared_dynamic_insert (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(255)     NULL,
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE
);
